"""Añadir importe_materiales a trabajo

Revision ID: 14f7ba081ea2
Revises: a2194afe5805
Create Date: 2025-06-11 07:46:29.666982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14f7ba081ea2'
down_revision = 'a2194afe5805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('importe_materiales', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajo', schema=None) as batch_op:
        batch_op.drop_column('importe_materiales')

    # ### end Alembic commands ###
