"""Cambio campo fecha a DateTime

Revision ID: 68ab8b147f20
Revises: 
Create Date: 2025-06-03 12:14:03.995541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ab8b147f20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajo', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.TEXT(),
               type_=sa.String(length=30),
               existing_nullable=True,
               existing_server_default=sa.text("'sin terminar'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajo', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.String(length=30),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'sin terminar'"))
        batch_op.alter_column('fecha',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
