"""Añadir tabla Factura y campo id_factura

Revision ID: a2194afe5805
Revises: c38ddab49485
Create Date: 2025-06-10 05:45:00.431597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2194afe5805'
down_revision = 'c38ddab49485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_factura', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_trabajo_id_factura', 'factura', ['id_factura'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajo', schema=None) as batch_op:
        batch_op.drop_constraint('fk_trabajo_id_factura', type_='foreignkey')
        batch_op.drop_column('id_factura')

    # ### end Alembic commands ###
