"""Añade hora de fin (fecha_fin) a Trabajo

Revision ID: c38ddab49485
Revises: 68ab8b147f20
Create Date: 2025-06-03 12:26:00.193641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38ddab49485'
down_revision = '68ab8b147f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_fin', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajo', schema=None) as batch_op:
        batch_op.drop_column('fecha_fin')

    # ### end Alembic commands ###
